FROM azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0
WORKDIR /workspace

RUN --mount=type=cache,target=/var/cache/tdnf \
    tdnf -y install gcc golang pkgconfig build-essential libvirt-devel git glibc-static

