apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ch-cloudinit-dv
  labels:
    name: ch-cloudinit-dv
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    registry:
      url: "docker://docker.io/harshitg/ch-cloudinit-disk:mariner"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
    storageClassName: "local-path"
