apiVersion: v1
kind: Service
metadata:
  name: kubevirt-gc-test-ssh-service
spec:
  type: NodePort
  selector:
    kubevirt.io/vm: kubevirt-ch-vm
  ports:
    - port: 22
      targetPort: 22
      nodePort: 31000
